### ISSUE TITLE
multi_controlled_toffoli is not working properly!

### ISSUE THREAD

**Issue by Biswayan375** [LegacYFTw/QuDiet#17]
![Screenshot from 2024-01-20 22-05-36](https://github.com/LegacYFTw/QuDiet/assets/67852792/1556d980-d134-40b8-9c69-3f22db49a95c)

When only one CONTROL is ON, the TARGET bit flips and also the ```multi_controlled_toffoli``` function is just a wrapper around the ```toffoli``` function.

**Comment by LegacYFTw** [comment]
Hi, thanks for using our software. I'm tagging @arnavdas88 to look into this if possible :)

**Comment by arnavdas88** [comment]
On it @LegacYFTw @Biswayan375

**Comment by arnavdas88** [comment]
@Biswayan375 , You can check the code now,

```python
from qudiet.core.quantum_circuit import QuantumCircuit

N = 5
qc = QuantumCircuit(

    # Represents the dimension of each quantum register
    qregs=[4 for _ in range(N)] + [2],

    # Represents the initial states
    init_states=[0 for _ in range(N+1)],
)

qc.h(5)
qc.toffoli(([1, 2, 3, 5], 4), 1)

qc.measure_all()

print(qc.run())
```

This works properly!! The MCT have been merged with toffoli implementation for now! Commit: https://github.com/LegacYFTw/QuDiet/commit/e321713d78c6ee06a28cabf58b138f9ce973edf0
